spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration

    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html

  messages:
    basename: messages/messages-ko
    encoding: UTF-8

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
    - classpath*:store/csolved/csolved/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${BUCKET_NAME}
    region: ${AWS_REGION}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  server:
    port: ${PROMETHEUS_PORT}

server:
  servlet:
    session:
      timeout: 720m
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  level:
    root: INFO
    store.csolved.csolved.domain.post.mapper.store.csolved.csolved.domain.community.mapper.CommunityMapper: TRACE
